spring.application.name=EcomPro1


spring.datasource.url=jdbc:mysql://localhost:3306/ecomdata
spring.datasource.username=root
spring.datasource.password=karthikeyan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
